/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPopRouteImport } from './routes/app.pop'
import { Route as AppPopHistoryRouteImport } from './routes/app.pop-history'
import { Route as AppPopReturnRouteImport } from './routes/app.pop-return'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppPosHistoryRouteImport } from './routes/app.pos-history'
import { Route as AppPosReturnRouteImport } from './routes/app.pos-return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPopRoute = AppPopRouteImport.update({
  id: '/pop',
  path: '/pop',
  getParentRoute: () => AppRoute,
} as any)
const AppPopHistoryRoute = AppPopHistoryRouteImport.update({
  id: '/pop-history',
  path: '/pop-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPopReturnRoute = AppPopReturnRouteImport.update({
  id: '/pop-return',
  path: '/pop-return',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPosHistoryRoute = AppPosHistoryRouteImport.update({
  id: '/pos-history',
  path: '/pos-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPosReturnRoute = AppPosReturnRouteImport.update({
  id: '/pos-return',
  path: '/pos-return',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/pop': typeof AppPopRoute
  '/app/pop-history': typeof AppPopHistoryRoute
  '/app/pop-return': typeof AppPopReturnRoute
  '/app/pos': typeof AppPosRoute
  '/app/pos-history': typeof AppPosHistoryRoute
  '/app/pos-return': typeof AppPosReturnRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/pop': typeof AppPopRoute
  '/app/pop-history': typeof AppPopHistoryRoute
  '/app/pop-return': typeof AppPopReturnRoute
  '/app/pos': typeof AppPosRoute
  '/app/pos-history': typeof AppPosHistoryRoute
  '/app/pos-return': typeof AppPosReturnRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/pop': typeof AppPopRoute
  '/app/pop-history': typeof AppPopHistoryRoute
  '/app/pop-return': typeof AppPopReturnRoute
  '/app/pos': typeof AppPosRoute
  '/app/pos-history': typeof AppPosHistoryRoute
  '/app/pos-return': typeof AppPosReturnRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/pop'
    | '/app/pop-history'
    | '/app/pop-return'
    | '/app/pos'
    | '/app/pos-history'
    | '/app/pos-return'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/pop'
    | '/app/pop-history'
    | '/app/pop-return'
    | '/app/pos'
    | '/app/pos-history'
    | '/app/pos-return'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/pop'
    | '/app/pop-history'
    | '/app/pop-return'
    | '/app/pos'
    | '/app/pos-history'
    | '/app/pos-return'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pop': {
      id: '/app/pop'
      path: '/pop'
      fullPath: '/app/pop'
      preLoaderRoute: typeof AppPopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pop-history': {
      id: '/app/pop-history'
      path: '/pop-history'
      fullPath: '/app/pop-history'
      preLoaderRoute: typeof AppPopHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pop-return': {
      id: '/app/pop-return'
      path: '/pop-return'
      fullPath: '/app/pop-return'
      preLoaderRoute: typeof AppPopReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos-history': {
      id: '/app/pos-history'
      path: '/pos-history'
      fullPath: '/app/pos-history'
      preLoaderRoute: typeof AppPosHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos-return': {
      id: '/app/pos-return'
      path: '/pos-return'
      fullPath: '/app/pos-return'
      preLoaderRoute: typeof AppPosReturnRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPopRoute: typeof AppPopRoute
  AppPopHistoryRoute: typeof AppPopHistoryRoute
  AppPopReturnRoute: typeof AppPopReturnRoute
  AppPosRoute: typeof AppPosRoute
  AppPosHistoryRoute: typeof AppPosHistoryRoute
  AppPosReturnRoute: typeof AppPosReturnRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPopRoute: AppPopRoute,
  AppPopHistoryRoute: AppPopHistoryRoute,
  AppPopReturnRoute: AppPopReturnRoute,
  AppPosRoute: AppPosRoute,
  AppPosHistoryRoute: AppPosHistoryRoute,
  AppPosReturnRoute: AppPosReturnRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
